### ISSUE TITLE
Docs unavailable

### ISSUE THREAD

**Issue by Dahie** [diablourbano/grapevine#8]
Hi

With the website down, the linked documentation is not available anymore. Can you copy it into the project or the wiki, please?

Also what's the state of the project, will it continue in the future?

regards, Daniel

**Comment by diablourbano** [comment]
hi @Dahie thank you so much for keeping an eye on this one, I just updated the url for the documentation, just in case is (this one)[http://diablourbano.com/grapevine/]

Sorry for the delay in the response, I'm trying to get time to fix this kind of issues.

Anyway, about the state of the project, I'm really happy to know there're some people who at least had considered to check it, however if you check (grape)[http://www.ruby-grape.org] you'll find they have included a lot of functionality which makes this project outdated. If you find any bug please let me know, so I can fix it, but new features or version updates, honestly, I don't think they will appear.

Thanks again, knowing someone saw this made my day :)

**Comment by Dahie** [comment]
You're welcome, thank you! :)
